---
title: "Chapter 14: Storing and Modifying Data"
output: html_notebook
---

# Setup Database

```{r setup}
library(pacman)
p_load(dplyr, DBI)

# Create a database table in memory
farmers.db <- 
  dbConnect(RMariaDB::MariaDB(), 
            group = "/Users/nickjenkins/Documents/Workshops & Conferences/SQL for Data Scientists/SQL for Data Scientists support files/FarmersMarketDatabase.sql",
            username = "root",
            password = "Hockeydude25",
            host = "localhost",
            port = 3306)
```

# Storing SQL Datasets as Tables and Views

You can store the results of a query as a table or a view. Storing them as a *table* takes a snapshot of whatever the results are at the time the query is run and saves the data returned as a new table object, or as new rows appended to an existing table. A database *view* stores the SQL itself and runs it on-demand when you write a query that references the name of the view.

One way to store the results of a query is to use a `CREATE TABLE` statement:

```{sql eval = FALSE}
CREATE TABLE[schema_name].[new_table_name] AS
(
  [your query here]
)
```

To delete a table, use `DROP`:

```{sql eval = FALSE}
DROP TABLE [schema_name].[table_name]
```

To create, select from, and drop a table that contains a snapshot of the data that is currently in the Farmer's Market database `product` table, filtered to products with a quantity type "unit" run the following three queries in sequence:

```{sql, connection = farmers.db}
CREATE TABLE farmers_market.product_units AS
(
  SELECT *
  FROM farmers_market.product
  WHERE product_qty_type = "unit"
)
;

SELECT *
FROM farmers_market.product_units
;

DROP TABLE farmers_market.product_units
;
```

Database views are created in a very similar way.

```{sql connection = farmers.db}
CREATE VIEW farmers_market.product_units_vw AS
(
  SELECT *
  FROM farmers_market.product
  WHERE product_qty_type = "unit"
)
;

SELECT *
FROM farmers_market.product_units_vw
;

DROP VIEW farmers_market.product_units_vw
;
```

# Adding a Timestamp Column

When creating or modifying a database table, you might want to keep a record of when each row in the table was created or last modified. You can do with by adding a timestamp column to your `CREATE TABLE` or `UPDATE` statement.

```{sql connection = farmers.db}
CREATE TABLE darmers_market.product_units AS
(
  SELECT
    p.*,
    CURRENT_TIMESTAMP AS snapshot_timestamp
  FROM farmers_market.product AS p
  WHERE product_qty_type = "unit"
)
```

# Inserting Rows and Updating Values in Database Tables

If you want to modify data in an existing database table, you can use an `INSERT` statement to add a new row or an `UPDATE` statement to modify an existing row of data in a table. In this chapter, we're specifically inserting results of a query into another table, which is a specific kind of `INSERT` statement called `INSERT INTO SELECT`. The syntax is:

```{sql eval = FALSE}
INSERT INTO [schema_name].[table_name]([comma-separated list of column names])
[your SELECT query here]
```

If we wanted to add rows to our `product_units` table created earlier, we would write:

```{sql connection = farmers.db}
INSERT INTO farmers_market.product_units (product_id, product_name, product_size,
product_category_id, product_qty_type, snapshot_timestamp)
SELECT
  product_id,
  product_name,
  product_size,
  product_category_id,
  product_qty_type,
  CURRENT_TIMESTAMP
FROM farmers_market.product AS p
WHERE product_id = 23
```

If you make a mistake when inserting a row and want to delete it, the syntax is simply

```{sql eval = FALSE}
DELETE FROM [schema_name].[table_name]
WHERE [set of conditions that uniquely identifies the row]
```

The `product_id` and `snapshot_timestamp` uniquely identify rows in the `product_units` table, so we can run the following statement to delete the row added by out previous `INSERT INTO`:

```{sql eval = FALSE}
DELECT FROM farmers_market.product_units
WHERE product_id = 23
  AND snapshot_timestamp = "2021-04-18 00:49:24"
```

You can update a value in an existing row without inserting a totally new row with the `UPDATE` statement:

```{sql eval = FALSE}
UPDATE [schema_name].[table_name]
SET [column_name] = [new value]
WHERE [set of conditions that uniquely identifies the rows you want to change]
```

# Using SQL Inside Scripts

You can write SQL code in other programming languages like R and Python.

# Exercises

1.  If you include a `CURRENT_TIMESTAMP` column when you create a view, what would your expect the values of that column to be when you query the view?

    Views are dynamically updated, so I would expect it to be equal to the time that the view was queried.

2.  Write a query to determine what the data from the `vendor_booth_assignment` table looked like on October 3, 2020 by querying the `vendor_booth_log` table created in the chapter.

    ```{sql eval = FALSE, connection = farmers.db}

    ```
