---
title: "Chapter 8: Date and Time Functions"
output: html_notebook
---

# Setup the Database

```{r setup}
library(pacman)
p_load(dplyr, DBI)

# Create a database table in memory
farmers.db <- 
  dbConnect(RMariaDB::MariaDB(), 
            group = "/Users/nickjenkins/Documents/Workshops & Conferences/SQL for Data Scientists/SQL for Data Scientists support files/FarmersMarketDatabase.sql",
            username = "root",
            password = "Hockeydude25",
            host = "localhost",
            port = 3306)
```

# Date and Time Functions

Time is important because many predictive models are time-bound. "Will this first-time customer become a repeat customer?" will be further refined as "What is the likelihood that each first-time customer at today's farmer's market will return and make a second purchase within the next month?" To answer this question, we could create a dataset with a row for every customer, columns containing data values as of the time of their first purchase, and a binary "target variable" that indicates whether that customer made another purchase within a month of their first purchase date.

# Setting datetime Field Values

The Farmer's Market `market_date_info` table doesn't include any fields stored as datetime values, so in order to demonstrate date and time functions without having to combine fields in every query, I'm going to first create a demonstration table with datetime created by combining the `market_date` and `market_start_time` in the `market_date_info` table using the following query:

```{sql connection = farmers.db}
CREATE TABLE farmers_market.datetime_demo AS
(
  SELECT 
    market_date,
    market_start_time,
    market_end_time,
    STR_TO_DATE(CONCAT(market_date, " ", market_start_time), "%Y-%m-%d %h:%i %p")
      AS market_start_datetime,
    STR_TO_DATE(CONCAT(market_date, " ", market_end_time), "%Y-%m-%d %h:%i %p")
      AS market_end_datetime
  FROM farmers_market.market_date_info
)
```

# `EXTRACT` and `DATE_PART`

The following query demonstrates five different "date parts" that can be extracted from the datetime and results in the output shown in Figure 8.2.

```{sql fig-8.2, connection = farmers.db}
SELECT
  market_start_datetime,
  EXTRACT(DAY FROM market_start_datetime) AS mktsrt_day,
  EXTRACT(MONTH FROM market_start_datetime) AS mktsrt_month,
  EXTRACT(YEAR FROM market_start_datetime) AS mktsrt_year,
  EXTRACT(HOUR FROM market_start_datetime) AS mktsrt_hour,
  EXTRACT(MINUTE FROM market_start_datetime) AS mktsrt_minute
FROM farmers_market.datetime_demo
WHERE market_start_datetime = "2019-03-02 08:00:00"
```

There are also shortcuts for extracting the entire date and entire time from the datetime field, so you don't have to extract each part and re-concatenate it together.

```{sql fig-8.3, connection = farmers.db}
SELECT
  market_start_datetime,
  DATE(market_start_datetime) AS mktsrt_date,
  TIME(market_start_datetime) AS mktsrt_time
FROM farmers_market.datetime_demo
WHERE market_start_datetime = "2019-03-02 08:00:00"
```

# `DATE_ADD` and `DATE_SUB`

If you wanted to determine how many sales occurred within the first 30 minutes after the farmer's market opened, how would you dynamically determine what cutoff time to use? This is where the `DATE_ADD` function comes in.

```{sql fig-8.4, connection = farmers.db}
SELECT
  market_start_datetime,
  DATE_ADD(market_start_datetime, INTERVAL 30 MINUTE) AS mktstrt_date_plus_30min
FROM farmers_market.datetime_demo
WHERE market_start_datetime = "2019-03-02 08:00:00"
```

We could also add 30 days to a date.

```{sql fig-8.5, connection = farmers.db}
SELECT
  market_start_datetime,
  DATE_ADD(market_start_datetime, INTERVAL 30 DAY) AS mktstrt_date_plus_30days
FROM farmers_market.datetime_demo
WHERE market_start_datetime = "2019-03-02 08:00:00"
```

The `DATE_SUB()` function subtracts intervals from datetimes (you could also just add a negative number to the datetime if you prefer).

```{sql fig-8.6, connection = farmers.db}
SELECT
  market_start_datetime,
  DATE_ADD(market_start_datetime, INTERVAL -30 DAY) AS mktstrt_date_plus_neg30days,
  DATE_SUB(market_start_datetime, INTERVAL 30 DAY) AS mktstrt_date_sub_30days
FROM farmers_market.datetime_demo
WHERE market_start_datetime = "2019-03-02 08:00:00"
```

# `DATEDIFF`

`DATEDIFF()` returns the difference between two dates.

In this query, the inner query, returns the first and last market dates from the `date_time_demo` table, and the outer query calculates the difference between those two dates using `DATEDIFF`.

```{sql fig-8.7, connection = farmers.db}
SELECT
  x.first_market,
  x.last_market,
  DATEDIFF(x.last_market, x.first_market) days_first_to_last
FROM
(
  SELECT
    MIN(market_start_datetime) first_market,
    MAX(market_start_datetime) last_market
  FROM farmers_market.datetime_demo
) x
```

# `TIMESTAMPDIFF`

`TIMESTAMPDIFF` returns the difference between two datetimes in any chosen interval. Here, we calculate the hours and minutes between the market start and end times on each market date.

```{sql fig-8.8, connection = farmers.db}
SELECT
  market_start_datetime, 
  market_end_datetime,
  TIMESTAMPDIFF(HOUR, market_start_datetime, market_end_datetime)
    AS market_duration_hours,
  TIMESTAMPDIFF(MINUTE, market_start_datetime, market_end_datetime)
    AS market_duration_mins
FROM farmers_market.datetime_demo
```

# Date Functions in Aggregate Summaries and Window Functions

Let's say we wanted to get a profile of each farmer's market customer's habits over time. So, we'll want to group the results at the customer level and include some date-related summary information in the output.

First, let's get each customer's purchase detail records - the dates on which each customer made purchases.

```{sql fig-8.9, connection = farmers.db}
SELECT
  customer_id, 
  market_date
FROM farmers_market.customer_purchases
WHERE customer_id = 1
```

Let's summarize this data and get their earliest purchase date, latest purchase date, and number of different days on which they made a purchase. We'll group by `cuatomer_id`, use `MIN` and `MAX` to get the lowest and highest purchase dates, and `COUNT DISTINCT` to determine on how many different dates they made purchases:

```{sql fig-8.10, connection = farmers.db}
SELECT 
  customer_id,
  MIN(market_date) AS first_purchase,
  MAX(market_date) AS last_purchase,
  COUNT(DISTINCT market_date) AS count_of_purchase_dates
FROM farmers_market.customer_purchases
WHERE customer_id = 1
GROUP BY customer_id
```

We can figure out how long this person has been a customer of the farmer's market but calculating the difference between the first and last purchase.

```{sql fig-8.11, connection = farmers.db}
SELECT customer_id,
  MIN(market_date) AS first_purchase,
  MAX(market_date) AS last_purchase,
  COUNT(DISTINCT market_date) AS count_of_purchase_dates,
  DATEDIFF(MAX(market_date), MIN(market_date)) AS days_between_first_last_purchase
FROM farmers_market.customer_purchases
GROUP BY customer_id
```

If we also wanted to know how long it's been since the customer last made a purchase, we can use the `CURDATE()` function which represents the current system time.

```{sql connection = farmers.db}
SELECT customer_id,
  MIN(market_date) AS first_purchase,
  MAX(market_date) AS last_purchase,
  COUNT(DISTINCT market_date) AS count_of_purchase_dates,
  DATEDIFF(MAX(market_date), MIN(market_date)) AS days_between_first_last_purchase,
  DATEDIFF(CURDATE(), MAX(market_date)) AS days_since_last_purchase
FROM farmers_market.customer_purchases
GROUP BY customer_id
```

With window functions, we can also write a query that gives the days between each purchase a customer makes.

```{sql fig-8.12, connection = farmers.db}
SELECT 
  customer_id,
  market_date,
  RANK() OVER (PARTITION BY customer_id ORDER BY market_date) AS purchase_number,
  LEAD(market_date, 1) OVER (PARTITION BY customer_id ORDER BY market_date)
    AS next_purchase
FROM farmers_market.customer_purchases
WHERE customer_id = 1
```

This query didn't retrieve each purchase date and the previous purchase date to get the time between them because there are multiple rows with the same date. We can resolve this by removing duplicates in the initial dataset and use a subquery to get the date differences.

```{sql fig-8.13, connection = farmers.db}
SELECT
  x.customer_id,
  x.market_date,
  RANK() OVER (PARTITION BY x.customer_id ORDER BY x.market_date)
    AS purchase_number,
  LEAD(x.market_date, 1) OVER (PARTITION BY x.customer_id ORDER BY x.market_date)
    AS next_purchase
FROM (
  SELECT DISTINCT customer_id, market_date
  FROM farmers_market.customer_purchases
  WHERE customer_id = 1
) x
```

Now we add a line to the query to use the `next_purchase` date in a `DATEDIFF` calculation:

```{sql connection = farmers.db}
SELECT
  x.customer_id,
  x.market_date,
  RANK() OVER (PARTITION BY x.customer_id ORDER BY x.market_date)
    AS purchase_number,
  LEAD(x.market_date, 1) OVER (PARTITION BY x.customer_id ORDER BY x.market_date)
    AS next_purchase,
  DATEDIFF(
    LEAD(x.market_date, 1) OVER 
    (PARTITION BY x.customer_id ORDER BY x.market_date),
    x.market_date
  ) AS days_between_purchases
FROM (
  SELECT DISTINCT customer_id, market_date
  FROM farmers_market.customer_purchases
  WHERE customer_id = 1
) x
```

We can avoid using the `LEAD()` function in the `DATEDIFF()` function, we could use a query of a query of a query:

```{sql fig-8.14, connection = farmers.db}
SELECT 
 a.customer_id, 
 a.market_date AS first_purchase, 
 a.next_purchase AS second_purchase,
 DATEDIFF(a.next_purchase, a.market_date) AS time_between_1st_2nd_purchase
FROM
(
 SELECT 
 x.customer_id,
 x.market_date,
 RANK() OVER (PARTITION BY x.customer_id ORDER BY x.market_date) 
  AS purchase_number,
 LEAD(x.market_date,1) OVER (PARTITION BY x.customer_id ORDER BY x.market_date) 
  AS next_purchase
FROM
 ( 
 SELECT DISTINCT customer_id, market_date
 FROM farmers_market.customer_purchases
 ) x
) a
WHERE a.purchase_number = 1
```

Let's say today's date is April 30, 2019 and the marketing director of the farmer's market wants to give infrequent customers an incentive to return to the market in April. The director asks you for a list of everyone who only made a purchase at one market event during the previous month, because they want to send an email to all of those customers with a coupon to receive a discount on a purchase made in April. We do this by first finding everyone who made a purchase in the 31 days prior to April 30, 2019. Then we need to filter that list to those who only made a purchase on a single market date during that time.

```{sql connection = farmers.db}
SELECT DISTINCT customer_id, market_date
FROM farmers_market.customer_purchases
WHERE DATEDIFF("2019-04-30", market_date) <= 30
```

Then, we query the the results of that query, count the distinct `market_date` values per customer during that time, and filter to those with exactly one market date, using the `HAVING` clause.

```{sql fig-8.15, connection = farmers.db}
SELECT 
  x.customer_id,
  COUNT(DISTINCT x.market_date) AS market_count
FROM
(
  SELECT DISTINCT customer_id, market_date
  FROM farmers_market.customer_purchases
  WHERE DATEDIFF("2019-03-30", market_date) <= 30
) x
GROUP BY x.customer_id
HAVING COUNT(DISTINCT market_date) = 1
```

# Exercises

1.  Get the `customer_id`, month, and year of every purchase in the `farmers_market.customer_purchases` table.

    ```{sql ex1, connection = farmers.db}
    SELECT 
      customer_id,
      EXTRACT(MONTH FROM market_date) AS purchase_month,
      EXTRACT(YEAR FROM market_date) AS purchase_year
    FROM farmers_market.customer_purchases
    ```

2.  Write a query that filters to purchases made in the past two weeks, returns the earliest `market_date` in that range as a field called `sales_since_date`, and a sum of the sales (`quantity * cost_to_customer_per_qty`) during that date range.

    Your final answer should use the `CURDATE()` function, but if you want to test it out on the Farmer's Market database, you can replace your `CURDATE()` with the value "2019-03-31" to get the report for the two weeks prior to March 31, 2019.

    ```{sql ex2, connection = farmers.db}
    SELECT 
      MIN(market_date) AS sales_since_date,
      SUM(quantity * cost_to_customer_per_qty) AS total_sales
    FROM farmers_market.customer_purchases
    WHERE DATEDIFF("2019-03-31", market_date) <= 14
    GROUP BY market_date
    ```

3.  In MySQL, there is a `DAYNAME()` function that returns the full name of the day of the week on which a date occurs. Query the Farmer's Market database `market_date_info` table, return the `market_date`, the `market_day`, and your calculated day of the week name that each `market_date` occurred on. Create a calculated column using a `CASE` statement that indicates whether the recorded day in the database differs from your calculated day of the week. This is an example of a quality control query that could be used to check manually entered data for correctness.

    ```{sql ex3, connection = farmers.db}
    SELECT
      market_date,
      market_day,
      DAYNAME(market_date) AS calc_day_name,
      CASE WHEN DAYNAME(market_date) = market_day THEN "Correct" ELSE "Incorrect"
        END AS qual_check
    FROM farmers_market.market_date_info
    ```
